<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SATHIYA-PC" failures="1" tests="12" name="org.kgisl.testScenario.TestCase_RegisterPage" time="15.932" errors="0" timestamp="2025-05-12T11:08:34 IST" skipped="0">
  <testcase classname="org.kgisl.testScenario.TestCase_RegisterPage" name="Test_10" time="1.404"/>
  <testcase classname="org.kgisl.testScenario.TestCase_RegisterPage" name="Test_3" time="1.553"/>
  <testcase classname="org.kgisl.testScenario.TestCase_RegisterPage" name="Test_11" time="1.567"/>
  <testcase classname="org.kgisl.testScenario.TestCase_RegisterPage" name="Test_12" time="1.351">
    <failure message="The following asserts failed:
	Register is failed expected [https://notes-mern-hlxh.onrender.com/login] but found [https://notes-mern-hlxh.onrender.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Register is failed expected [https://notes-mern-hlxh.onrender.com/login] but found [https://notes-mern-hlxh.onrender.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at org.kgisl.testScenario.TestCase_RegisterPage.Test_12(TestCase_RegisterPage.java:282)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Test_12 -->
  <testcase classname="org.kgisl.testScenario.TestCase_RegisterPage" name="Test_7" time="1.210"/>
  <testcase classname="org.kgisl.testScenario.TestCase_RegisterPage" name="Test_6" time="1.094"/>
  <testcase classname="org.kgisl.testScenario.TestCase_RegisterPage" name="Test_2" time="1.064"/>
  <testcase classname="org.kgisl.testScenario.TestCase_RegisterPage" name="Test_8" time="1.185"/>
  <testcase classname="org.kgisl.testScenario.TestCase_RegisterPage" name="Test_5" time="1.128"/>
  <testcase classname="org.kgisl.testScenario.TestCase_RegisterPage" name="Test_9" time="1.707"/>
  <testcase classname="org.kgisl.testScenario.TestCase_RegisterPage" name="Test_1" time="1.490"/>
  <testcase classname="org.kgisl.testScenario.TestCase_RegisterPage" name="Test_4" time="1.179"/>
</testsuite> <!-- org.kgisl.testScenario.TestCase_RegisterPage -->
